---
title: "iLINCS API R Notebook - Creating a signature from dataset"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

## Prerequisites 

```{r}
library(knitr)
library(tinytex)
library(httr)
library(jsonlite)
library(plotly)
```

### List of LINCS Datasets
```{r}
apiUrl <- "http://www.ilincs.org/api/PublicDatasets/getDatasets?lincs=true"
req <- GET(apiUrl)
json <- httr::content(req, as = "text")
lincs_datasets <- fromJSON(json)
lincsDatasets <- data.frame(lincs_datasets$data)
lincsDatasets[c("experiment","assay","dataType")]
```


### Dataset metadata

**Example:** EDS-1014  
```{r}
experiment <- "EDS-1014"

apiUrl <- paste("http://www.ilincs.org/api/PublicDatasets/",experiment,sep="")
req <- GET(apiUrl)
json <- httr::content(req, as = "text")
datasetMetaData <- fromJSON(json)
# datasetMetaData <- data.frame(datasetMeta)
datasetMetaData
```

[Heatmap for dataset `r experiment` on iLINCS](http://www.ilincs.org/apps/heatmap/?data_set=`r experiment`)

[PCA and tSNE for dataset `r experiment` on iLINCS](http://www.ilincs.org/apps/pca/?data_set=`r experiment`)

### Dataset sample metadata


```{r}
apiUrl <- paste("http://www.ilincs.org/api/ilincsR/getSamples?id=",experiment,sep="")
req <- GET(apiUrl)
json <- httr::content(req, as = "text")
sampleMeta <- fromJSON(json)
sampleMetaData <- data.frame(sampleMeta$data$rows)
sampleMetaData
# sampleMetaData[c("experiment","assay","dataType")]
```

[Create signature from dataset `r experiment` on iLINCS](http://www.ilincs.org/ilincs/dataset/`r experiment`/createSignature)

### Heatmap

```{r, out.width="910px"}
include_url("http://www.ilincs.org/apps/heatmap/?sessionID=Wed_Nov_28_14_02_36_2018_3471356&property=CK14&geneCount=100", height = "900px")
# htmltools::includeHTML("<a href='http://www.ilincs.org/apps/heatmap/?sessionID=Wed_Nov_28_14_02_36_2018_3471356&property=CK14&geneCount=100' target='_blank'>Heatmap</a>")
knit_print("<a href='http://www.ilincs.org/apps/heatmap/?sessionID=Wed_Nov_28_14_02_36_2018_3471356&property=CK14&geneCount=100'>abc</a>")
normal_print("<a href='http://www.ilincs.org/apps/heatmap/?sessionID=Wed_Nov_28_14_02_36_2018_3471356&property=CK14&geneCount=100'>abc</a>")
cat("[Region:](www.somewebsite.com)")
heatmap_url<-"http://www.ilincs.org/apps/heatmap/?sessionID=Wed_Nov_28_14_02_36_2018_3471356&property=CK14&geneCount=100"
```

### `r heatmap_url`

[Heatmap](`r heatmap_url`)

